---
kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: NAMESPACE
    displayName: Namespace
    required: true
  - name: URL
    displayName: URL
    description: 'URL where the application will be available, eg: hms-api-develop.apps.silver.devops.gov.bc.ca'
    required: true
objects:
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: hms-api
      namespace: ${NAMESPACE}
    spec:
      host: ${URL}
      path: /
      to:
        kind: Service
        name: hms-api
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-all-ingress-hms-api
      namespace: ${NAMESPACE}
    spec:
      podSelector:
        matchLabels:
          name: hms-api
      ingress:
        - {}
      policyTypes:
        - Ingress
  - kind: Service
    apiVersion: v1
    metadata:
      name: hms-api
      namespace: ${NAMESPACE}
    spec:
      selector:
        name: hms-api
      ports:
        - name: http
          port: 80
          targetPort: 3000
