name: Enforce Pull Request Rules

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Pull Requests Against `main`
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "Error: You can only merge to `main` from `develop`."
          exit 1
      - name: Check Pull Requests Against `develop`
        if: github.base_ref == 'develop' && github.head_ref == 'main'
        run: |
          echo "Error: You can't merge to `develop` from `main`."
          exit 1
